name: generate-images
on:
  pull_request:
    branches: [main]
    paths:
      - '**/*.mermaid'
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get source changes
        id: source_changes
        run: |
          echo "::set-output name=files::$(git diff --name-only remotes/origin/$GITHUB_BASE_REF | grep -e '.*\.mermaid$' | xargs)"
      - name: Show source changes
        run: |
          echo ${{ steps.source_changes.outputs.files }}
      - name: Compile mermaid
        if: steps.source_changes.outputs.files != ''
        uses: neenjaw/compile-mermaid-markdown-action@0.2.4
        with:
          files: ${{ steps.source_changes.outputs.files }}
          output: 'images'
      - name: Get result changes
        id: result_changes
        run: |
          echo "::set-output name=files::$(git status -s)"
      - name: Show result changes
        if: steps.source_changes.outputs.files != ''
        run: |
          echo ${{ steps.result_changes.outputs.files }}
      - name: Rename result files
        if: steps.source_changes.outputs.files != ''
        run: |
            for i in images/*-mermaid.png; do mv "$i" "${i%-mermaid.png}.png"; done
      - name: Commit files
        if: steps.result_changes.outputs.files != ''
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add images/*
          git commit -m "chore: generate images" images/*
      - name: Push changes
        if: steps.result_changes.outputs.files != ''
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
